### ISSUE TITLE
custom plugin options/settings page visible only in custom role's dashboard

### ISSUE THREAD

**Issue by steveadamsfixedit** [zahardoc/wp-plugin-boilerplate#2]
I'm building a plugin based on the boilerplate that contains analytics data on virtual events attended by logged in users. The entire system is restricted to a hierarchy of users from the top down as follows: Admins, Moderators, Presenters, Attendees. I've granted Moderators access to the WP dashboard where I want to display a 'settings/options' page where they can see the activity analytics data of the attendees for only the events that are under their moderation control. Admins should be able to see all event analytics for all events tied to all moderators. 
   Currently, I've constructed this page in my custom_plugin/admin/partials/custom_plugin-events.php file and it is displaying all the activity at an administrator level. Furthermore, I've constructed the custom post type for the events and the custom roles with access. The moderator can see the custom post type in their dashboard.
    My question is threefold:

1) How do I make the event analytics page at the wp-admin/admin.php?page=custom_plugin-events url visible in the moderator's dashboard?
2) I'm presently using some conditional logic in this admin/partial page that basically says if user_can=admin show this data and if user_can=moderator show this other data. Is that the correct and recommended approach? 
3) If I'm requiring all these users to be logged in and applied to one custom role or another...is the custom_plugin/admin directory  the correct place to implement this? or would it be better in custom_plugin/public?

**Comment by zahardev** [comment]
Hi @steveadamsfixedit!

Your question is not related to this project. It's just for starting to make your own things. It's up to you how you do it.
So I'm closing this issue. Good luck with your plugin!
